spring:
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  web:
    resources:
      cache:
        period: 0
      static-locations: file:src/main/resources/static/
